# Generated by Django 5.2.1 on 2025-06-06 19:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Característica')),
                ('icono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clase de Icono (ej. FontAwesome)')),
            ],
            options={
                'verbose_name': 'Característica del Vehículo',
                'verbose_name_plural': 'Características de Vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCarroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Carrocería')),
            ],
            options={
                'verbose_name': 'Tipo de Carrocería',
                'verbose_name_plural': 'Tipos de Carrocería',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Combustible')),
            ],
            options={
                'verbose_name': 'Tipo de Combustible',
                'verbose_name_plural': 'Tipos de Combustible',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Transmisión')),
            ],
            options={
                'verbose_name': 'Tipo de Transmisión',
                'verbose_name_plural': 'Tipos de Transmisión',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_fabricacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año de Fabricación')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Versión/Edición')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio de Venta')),
                ('kilometraje', models.PositiveIntegerField(verbose_name='Kilometraje Actual')),
                ('color_exterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Exterior')),
                ('color_interior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Interior')),
                ('numero_puertas', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Número de Puertas')),
                ('cilindraje_cc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cilindraje (cc)')),
                ('potencia_hp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Potencia (HP)')),
                ('descripcion_detallada', models.TextField(verbose_name='Descripción Detallada del Vehículo')),
                ('numero_chasis', models.CharField(max_length=17, unique=True, verbose_name='Número de Chasis (VIN)')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Número de Placa')),
                ('situacion_general', models.CharField(choices=[('excelente', 'Excelente Estado'), ('bueno', 'Buen Estado'), ('regular', 'Requiere Reparaciones Menores'), ('malo', 'Requiere Reparaciones Mayores (Siniestrado)'), ('partes', 'Para Partes/Repuestos (Siniestrado Grave)')], default='bueno', max_length=20, verbose_name='Situación General del Vehículo')),
                ('tiene_historial_siniestros', models.BooleanField(default=False, verbose_name='¿Tiene historial de siniestros/accidentes?')),
                ('detalle_historial_siniestros', models.TextField(blank=True, null=True, verbose_name='Detalle del Historial de Siniestros (fechas, tipo de daño, reparaciones)')),
                ('valor_avaluo_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Avalúo/Referencia (Catastro)')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('disponible_para_venta', models.BooleanField(default=True, verbose_name='¿Está disponible para venta?')),
                ('caracteristicas_adicionales', models.ManyToManyField(blank=True, to='Modulo3.caracteristicavehiculo', verbose_name='Características Adicionales')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_en_venta', to='Vehiculos.vehiculomarca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_en_venta', to='Vehiculos.vehiculomodelo', verbose_name='Modelo')),
                ('tipo_carroceria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Modulo3.tipocarroceria', verbose_name='Tipo de Carrocería')),
                ('tipo_combustible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Modulo3.tipocombustible', verbose_name='Tipo de Combustible')),
                ('tipo_transmision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Modulo3.tipotransmision', verbose_name='Tipo de Transmisión')),
            ],
            options={
                'verbose_name': 'Vehículo en Venta',
                'verbose_name_plural': 'Vehículos en Venta',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos_imagenes_venta/', verbose_name='Imagen del Vehículo')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Es Imagen Principal')),
                ('orden', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Orden de visualización')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Modulo3.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Imagen del Vehículo',
                'verbose_name_plural': 'Imágenes del Vehículo',
                'ordering': ['orden', '-es_principal', 'id'],
            },
        ),
    ]
