# Generated by Django 5.2.1 on 2025-07-04 10:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLocalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo en el Local')),
                ('fecha_inicio_laboral', models.DateField(help_text='Fecha en que el empleado comenzó a laborar en el local.', verbose_name='Fecha de Inicio Laboral')),
                ('user_profile', models.OneToOneField(limit_choices_to={'role': 'admin_local'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_local_details', to='Principal.userprofile', verbose_name='Perfil de Usuario (Administrador de Local)')),
            ],
            options={
                'verbose_name': 'Perfil de Administrador de Local',
                'verbose_name_plural': 'Perfiles de Administradores de Local',
                'ordering': ['user_profile__local__name', 'cargo'],
            },
        ),
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres del Cliente')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos del Cliente')),
                ('cedula', models.CharField(help_text='Número de cédula único del cliente.', max_length=10, unique=True, verbose_name='Cédula de Identidad')),
                ('email_contacto', models.EmailField(blank=True, help_text='Correo electrónico adicional para el cliente, si es diferente al de su cuenta.', max_length=254, null=True, verbose_name='Correo Electrónico de Contacto')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección del Cliente')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Teléfono')),
                ('user_profile', models.OneToOneField(limit_choices_to={'role': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_details', to='Principal.userprofile', verbose_name='Perfil de Usuario (Cliente)')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfiles de Clientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='ConvenioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, help_text='Descuento aplicado a las compras del cliente (rango de 1% a 10%).', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0, message='El descuento mínimo es 1%.'), django.core.validators.MaxValueValidator(10.0, message='El descuento máximo es 10%.')], verbose_name='Porcentaje de Descuento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se registró el convenio.', verbose_name='Fecha de Creación del Convenio')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el convenio está actualmente activo y el descuento es aplicable.', verbose_name='Convenio Activo')),
                ('cliente_profile', models.OneToOneField(help_text='Perfil del cliente asociado a este convenio.', on_delete=django.db.models.deletion.CASCADE, related_name='convenio', to='Principal.clienteprofile', verbose_name='Cliente en Convenio')),
            ],
            options={
                'verbose_name': 'Convenio de Cliente',
                'verbose_name_plural': 'Convenios de Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
