# Generated by Django 5.2.1 on 2025-07-15 18:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_cliente', models.CharField(help_text='Cédula del cliente asociado a este convenio.', max_length=10, unique=True)),
                ('nombre_convenio', models.CharField(help_text='Nombre del convenio (ej: Oro, Empleado).', max_length=100)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento para este convenio (ej. 10.50 para 10.5%).', max_digits=5)),
                ('activo', models.BooleanField(default=True, help_text='Indica si este convenio está activo.')),
            ],
        ),
        migrations.CreateModel(
            name='ConvenioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, help_text='Descuento aplicado a las compras del cliente (rango de 1% a 10%).', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0, message='El descuento mínimo es 1%.'), django.core.validators.MaxValueValidator(10.0, message='El descuento máximo es 10%.')], verbose_name='Porcentaje de Descuento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se registró el convenio.', verbose_name='Fecha de Creación del Convenio')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el convenio está actualmente activo y el descuento es aplicable.', verbose_name='Convenio Activo')),
                ('cliente_profile', models.OneToOneField(help_text='Perfil del cliente asociado a este convenio.', on_delete=django.db.models.deletion.CASCADE, related_name='convenio', to='Principal.clienteprofile', verbose_name='Cliente en Convenio')),
            ],
            options={
                'verbose_name': 'Convenio de Cliente',
                'verbose_name_plural': 'Convenios de Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
