# Generated by Django 5.2.1 on 2025-10-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_convenio_conveniocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Sube la imagen del slide.', upload_to='carousel_images/')),
                ('title', models.CharField(help_text="Título principal del slide (e.g., 'El mejor gimnasio').", max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text="Subtítulo/Texto pequeño (e.g., '¡Bienvenido!').", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción más larga.')),
                ('button_link', models.URLField(blank=True, help_text="URL a donde lleva el botón 'Learn More'.")),
                ('button_text', models.CharField(default='Ver Oferta', help_text='Texto del botón.', max_length=50)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='El número más bajo aparecerá primero.')),
                ('is_active', models.BooleanField(default=True, help_text='Desactiva para ocultar temporalmente sin borrar.')),
            ],
            options={
                'verbose_name': 'Slide del Carrusel',
                'verbose_name_plural': 'Slides del Carrusel',
                'ordering': ['order'],
            },
        ),
    ]
