# Generated by Django 5.2.7 on 2025-11-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_carouselslide'),
    ]

    operations = [
    ]
