# Generated by Django 5.2.7 on 2025-11-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0004_auto_20251130_0145'),
    ]

    operations = [
    ]
