# Generated by Django 5.2.1 on 2025-06-06 19:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoParteVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Parte')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Tipo de Parte')),
            ],
            options={
                'verbose_name': 'Tipo de Parte de Repuesto',
                'verbose_name_plural': 'Tipos de Partes de Repuestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio Unitario')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Stock')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU (Stock Keeping Unit)')),
                ('marca_fabricante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca del Fabricante del Repuesto')),
                ('tipo_motor_compatible', models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido'), ('n/a', 'No Aplica')], max_length=50, null=True, verbose_name='Tipo de Motor Compatible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto Activo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='Modulo2.categoria', verbose_name='Categoría')),
                ('compatibilidad_marcas', models.ManyToManyField(blank=True, related_name='productos_compatibles_por_marca', to='Vehiculos.vehiculomarca', verbose_name='Marcas Compatibles')),
                ('compatibilidad_modelos', models.ManyToManyField(blank=True, related_name='productos_compatibles_por_modelo', to='Vehiculos.vehiculomodelo', verbose_name='Modelos Compatibles')),
                ('tipo_parte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_por_tipo', to='Modulo2.tipopartevehiculo', verbose_name='Tipo de Parte del Vehículo')),
            ],
            options={
                'verbose_name': 'Producto de Repuesto',
                'verbose_name_plural': 'Productos de Repuestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos_imagenes/', verbose_name='Imagen del Producto')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Es Imagen Principal')),
                ('orden', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Orden de visualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Modulo2.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['orden', '-es_principal', 'id'],
            },
        ),
    ]
