# Generated by Django 5.2.1 on 2025-07-03 06:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cas_mod1', models.CharField(max_length=150, verbose_name='Nombre de la Característica')),
                ('descripcion_cas_mod1', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada de la Característica')),
            ],
            options={
                'verbose_name': 'Característica de Servicio',
                'verbose_name_plural': 'Características de Servicio',
                'ordering': ['tipo_mantenimiento_cas_mod1__nombre_tim_mod1', 'nombre_cas_mod1'],
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tim_mod1', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Mantenimiento')),
                ('descripcion_corta_tim_mod1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción Corta del Tipo')),
                ('imagen_destacada_tim_mod1', models.ImageField(blank=True, null=True, upload_to='tipos_mantenimiento_img/', verbose_name='Imagen Destacada del Tipo')),
                ('activo_tim_mod1', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado del Tipo de Mantenimiento')),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimiento',
                'ordering': ['nombre_tim_mod1'],
            },
        ),
        migrations.CreateModel(
            name='ServicioMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sem_mod1', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('descripcion_corta_sem_mod1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción Corta del Servicio')),
                ('descripcion_larga_sem_mod1', models.TextField(verbose_name='Descripción Detallada del Servicio')),
                ('precio_referencia_sem_mod1', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio de Referencia/Desde')),
                ('duracion_estimada_horas_sem_mod1', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Duración Estimada (horas)')),
                ('activo_sem_mod1', models.BooleanField(default=True, verbose_name='Servicio Activo en Catálogo')),
                ('fecha_creacion_sem_mod1', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion_sem_mod1', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('caracteristicas_detalladas_sem_mod1', models.ManyToManyField(blank=True, related_name='servicios_que_contienen_esta_caracteristica_mod1', to='Modulo1.caracteristicaservicio', verbose_name='Características Detalladas Incluidas')),
                ('compatibilidad_marcas_sem_mod1', models.ManyToManyField(blank=True, related_name='servicios_taller_compatibles_por_marca_mod1', to='Vehiculos.vehiculomarca', verbose_name='Marcas de Vehículo Compatibles')),
                ('compatibilidad_modelos_sem_mod1', models.ManyToManyField(blank=True, related_name='servicios_taller_compatibles_por_modelo_mod1', to='Vehiculos.vehiculomodelo', verbose_name='Modelos de Vehículo Compatibles')),
                ('tipo_mantenimiento_sem_mod1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_asociados', to='Modulo1.tipomantenimiento', verbose_name='Tipo de Mantenimiento Principal')),
            ],
            options={
                'verbose_name': 'Servicio de Mantenimiento',
                'verbose_name_plural': 'Servicios de Mantenimiento',
                'ordering': ['tipo_mantenimiento_sem_mod1__nombre_tim_mod1', 'nombre_sem_mod1'],
                'unique_together': {('tipo_mantenimiento_sem_mod1', 'nombre_sem_mod1')},
            },
        ),
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_ims_mod1', models.ImageField(upload_to='servicios_taller_img/', verbose_name='Archivo de Imagen')),
                ('descripcion_ims_mod1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de la Imagen')),
                ('es_principal_ims_mod1', models.BooleanField(default=False, verbose_name='¿Es la Imagen Principal?')),
                ('orden_ims_mod1', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Orden de visualización')),
                ('servicio_ims_mod1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_del_servicio', to='Modulo1.serviciomantenimiento', verbose_name='Servicio al que Pertenece la Imagen')),
            ],
            options={
                'verbose_name': 'Imagen de Servicio',
                'verbose_name_plural': 'Imágenes de Servicios',
                'ordering': ['servicio_ims_mod1__nombre_sem_mod1', 'orden_ims_mod1', '-es_principal_ims_mod1', 'id'],
            },
        ),
        migrations.AddField(
            model_name='caracteristicaservicio',
            name='tipo_mantenimiento_cas_mod1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas_del_tipo', to='Modulo1.tipomantenimiento', verbose_name='Tipo de Mantenimiento al que Pertenece'),
        ),
        migrations.AlterUniqueTogether(
            name='caracteristicaservicio',
            unique_together={('tipo_mantenimiento_cas_mod1', 'nombre_cas_mod1')},
        ),
    ]
