# Generated by Django 5.2.1 on 2025-07-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciomantenimiento',
            name='activo_sem_mod1',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado del Servicio en Catálogo'),
        ),
    ]
