# Generated by Django 5.2.1 on 2025-06-06 19:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas_logos_core/', verbose_name='Logo de la Marca')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la Marca')),
            ],
            options={
                'verbose_name': 'Marca de Vehículo (Core)',
                'verbose_name_plural': 'Marcas de Vehículos (Core)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VehiculoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Modelo')),
                ('anio_inicio_produccion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año Inicio Producción')),
                ('anio_fin_produccion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año Fin Producción')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Modelo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_relacionados', to='Vehiculos.vehiculomarca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo de Vehículo (Core)',
                'verbose_name_plural': 'Modelos de Vehículos (Core)',
                'ordering': ['marca__nombre', 'nombre'],
                'unique_together': {('marca', 'nombre')},
            },
        ),
    ]
